<!DOCTYPE html>
<html lang="pt-BR">
<head>
	<meta charset="UTF-8">
	<title>My-King</title>
	<link rel="stylesheet" href="templates/TMyKing/css/bootstrap.min.css" media="screen">
	<link rel="stylesheet" href="templates/TMyKing/css/bootstrap.css" media="screen">
<link rel="stylesheet" href="templates/TMyKing/css/docs.css" media="screen">

</head>
<body>

<!-- Menu -->
 <div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			




		</div>
	</div>
</div>
<!-- Fim do menu -->

<!-- Início do header -->
<div class="jumbotron masthead">

	<div class="container">

	<img src="public/images/logo.png">


	<h3>My-King - Framework PHP</h3>

	<p>
	<!-- <a href="#" class="btn btn-primary btn-large">Download</a> -->
	</p>

	</div>
</div>

<!-- Fim do header -->

<!-- Início do conteúdo -->

    <!-- Docs nav
    ================================================== -->
    <div class="row">
      <div class="span3 bs-docs-sidebar">
        <ul class="nav nav-list bs-docs-sidenav">
          <li><a href="#dropdowns"><i class="icon-chevron-right"></i> Getting Started</a></li>
          <li><a href="#buttonGroups"><i class="icon-chevron-right"></i> Hierarquia de pastas</a></li>
          <li><a href="#buttonDropdowns"><i class="icon-chevron-right"></i> Aplicação</a></li>
      </div>
      <div class="span9">


        <!-- Dropdowns
        ================================================== -->
        <section id="dropdowns">
          <div class="page-header">
			<h1>Getting Started</h1>
			<b>Entenda como o My-King funciona.</b>
          </div>

          <h2>Exemplo</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut felis interdum, pellentesque sem ut, dignissim lectus. Mauris convallis magna est.</p>
            <div class="dropdown clearfix">
			</div>
<pre class="prettyprint linenums">
</pre>

          <h2>Exemplo</h2>
         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut felis interdum, pellentesque sem ut, dignissim lectus. Mauris convallis magna est.</p>
 

<pre class="prettyprint linenums">
</pre>

          <h2>Exemplo</h2>
         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut felis interdum, pellentesque sem ut, dignissim lectus. Mauris convallis magna est.</p>
          
<pre class="prettyprint linenums">
</pre>

          <h2>Exemplo</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut felis interdum, pellentesque sem ut, dignissim lectus. Mauris convallis magna est, in egestas est consectetur eget. Nunc varius eget arcu ac vulputate. Duis dignissim ligula at euismod aliquet. Suspendisse lacinia urna non imperdiet fringilla. Praesent vel convallis nibh, nec egestas sem. Aliquam nec massa hendrerit, pellentesque velit sed, pharetra eros.</p>

<pre class="prettyprint linenums">
</pre>

        </section>



        <!-- Button Groups
        ================================================== -->
        <section id="buttonGroups">
          <div class="page-header">
			<h1>Hierarquia de pastas</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut felis interdum, pellentesque sem ut, dignissim lectus.</p>	
          </div>

          <h2>Exemplo</h2>

<pre class="prettyprint linenums">
</pre>

          <h2>Exemplo</h2>
         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut felis interdum, pellentesque sem ut, dignissim lectus.</p>	 
<pre class="prettyprint linenums">
</pre>

		  <h2>Exemplo</h2>
		  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut felis interdum, pellentesque sem ut, dignissim lectus.</p>
<pre class="prettyprint linenums">
</pre>


          <hr class="bs-docs-separator">


        </section>


        <!-- Split button dropdowns
        ================================================== -->
        <section id="buttonDropdowns">
          <div class="page-header">
            <h1>Aplicação</h1>
          </div>


          <h2>Exemplo</h2>
         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut felis interdum, pellentesque sem ut, dignissim lectus.</p>
 
<pre class="prettyprint linenums">
</pre>

          <h2>Exemplo</h2>
         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut felis interdum, pellentesque sem ut, dignissim lectus.</p>
 

<pre class="prettyprint linenums">
</pre>

      </div>
    </div>


	<!-- Footer -->
	<footer class="footer">
	
		<div class="container">

			<p class="pull-right"><a href="#">Voltar ao topo</a></p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor non eros placerat scelerisque. Nunc cursus lacinia auctor. Donec sed leo id magna scelerisque eleifend sit amet vel enim. Sed pulvinar hendrerit velit, vitae accumsan sapien commodo ac. Donec iaculis eu urna nec lobortis. Duis sit amet mattis justo. Ut eget purus vel diam commodo viverra.</p>


		</div>

	</footer>

<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="templates/TMyKing/js/bootstrap.min.js"></script>
</body>
</html>


