<!DOCTYPE html>
<html lang="pt-BR">
<head>
	<meta charset="UTF-8">
	<title>My-King</title>
	<link rel="stylesheet" href="templates/TMyKing/css/bootstrap.min.css" media="screen">
	<link rel="stylesheet" href="templates/TMyKing/css/bootstrap.css" media="screen">
<link rel="stylesheet" href="templates/TMyKing/css/docs.css" media="screen">

</head>
<body>

<!-- Menu -->
 <div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
	





		</div>
	</div>
</div>
<!-- Fim do menu -->

<!-- Início do header -->

<div class="jumbotron masthead">

	<div class="container">

	<img src="public/images/logo.png">


	<h3>My-King - Framework PHP</h3>

	<p>
	<a href="#" class="btn btn-primary btn-large">Download</a>
	</p>

	</div>
</div>
<!-- Fim do header -->

<!-- Início do conteúdo -->

	<div class="container">

		<div class="marketing">
			
			
				<h3>My-King é um Framework PHP no formato MVC</h3>
				<h1>Getting started</h1>
				<p class="marketing-byline">Aprenda a usar o My-King</p>


				<div class="row-fluid">

					<div class="span4">

						<h2>Para que tipo de usuário?</h2>

						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor non eros placerat scelerisque. Nunc cursus lacinia auctor. Donec sed leo id magna scelerisque eleifend sit amet vel enim. Sed pulvinar hendrerit velit, vitae accumsan sapien commodo ac. Donec iaculis eu urna nec lobortis. Duis sit amet mattis justo. Ut eget purus vel diam commodo viverra.</p>

					</div>				


					<div class="span4">

						<h2>Responsivo</h2>

						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor non eros placerat scelerisque. Nunc cursus lacinia auctor. Donec sed leo id magna scelerisque eleifend sit amet vel enim. Sed pulvinar hendrerit velit, vitae accumsan sapien commodo ac. Donec iaculis eu urna nec lobortis. Duis sit amet mattis justo. Ut eget purus vel diam commodo viverra.</p>


					</div>

					<div class="span4">

						<h2>Funcionalidades</h2>

						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor non eros placerat scelerisque. Nunc cursus lacinia auctor. Donec sed leo id magna scelerisque eleifend sit amet vel enim. Sed pulvinar hendrerit velit, vitae accumsan sapien commodo ac. Donec iaculis eu urna nec lobortis. Duis sit amet mattis justo. Ut eget purus vel diam commodo viverra.</p>


					</div>



				</div> <!-- fim do row fluid  -->

		<hr class="soften"> <!-- Divisor -->




		</div>

	</div> <!-- Fim do container -->


	<!-- Footer -->
	<footer class="footer">
	
		<div class="container">

			<p class="pull-right"><a href="#">Voltar ao topo</a></p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor non eros placerat scelerisque. Nunc cursus lacinia auctor. Donec sed leo id magna scelerisque eleifend sit amet vel enim. Sed pulvinar hendrerit velit, vitae accumsan sapien commodo ac. Donec iaculis eu urna nec lobortis. Duis sit amet mattis justo. Ut eget purus vel diam commodo viverra.</p>


		</div>

	</footer>

<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="templates/TMyKing/js/bootstrap.min.js"></script>
</body>
</html>


