<br/>
<br/>
<pre class="prettyprint linenums">
&lt;?php

    /**
     * MyKing Framework PHP.
     * @package my-king
     * @link https://github.com/my-king/my-king/
     * @version 1.0
     * @author Igor da Hora &lt;igordahora@gmail.com&gt;
     * @author Marley Oliveira &lt;rmarlley@gmail.com&gt;
     * @author Samuel Guimaraes &lt;samucaguimaraes@gmail.com&gt;
     * @author Jonas Silva &lt;jonslipk@gmail.com&gt;
     * @license http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License
     * @note Este programa é distribuido na esperança que possa ser  util, mas 
     * SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
     * MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a Licença Pública Geral GNU 
     * para maiores detalhes.
     */

    // Exemplo de comentario 2
    class IndexController extends TMetroUI{
    # Exemplo de comentario 3
        public function index() {
            $this->TPageStart('index');
        }

    }
?&gt;
</pre>